### ISSUE TITLE
Reloading panel app causes few seconds of lag

### ISSUE THREAD

**Issue by Marsolo1** [clement-moulin-frier/vivarium#16]
### Description
The first time the panel app is opened in a browser, everything works fine. However if the page refreshes (automatically by modifying the code and saving with `--autoreload` active, or manually by reloading the page) the app seems to be out of sync with the server for a few seconds, falling to 3~4 FPS.

### Steps to Reproduce
- Launch the server
- Launch the interface
- Open the app in a web browser (http://localhost:5006/panel_app)
- Reload the page

**Comment by corentinlger** [comment]
Nothing fixed, comes from Panel side
