### ISSUE TITLE
Implement saving/loading a simulation

### ISSUE THREAD

**Issue by clement-moulin-frier** [clement-moulin-frier/vivarium#30]
### Description
A possible design (but other could also works):

In the Simulator class, implement methods:

- start_recording
- stop_recording
- save
- load

This way, there would be nothing to change in the interface

### Steps to Reproduce
[//]: # (List the steps to reproduce the issue.)

### Environment (Optional)
- OS: 
- Browser: 
- Python Version:
- Package Version: 

### Screenshots (Optional)
[//]: # (If applicable, add screenshots to help explain the issue.)

**Comment by corentinlger** [comment]
Done in #85
