### ISSUE TITLE
Make a notebook tutorial inspired by session 1 of pyvrep-epuck

### ISSUE THREAD

**Issue by clement-moulin-frier** [clement-moulin-frier/vivarium#33]
### Description

Session 1 of pyvrep-epuck consists of:

- Description of the simulator
- First description of how to interact with it from 
- Implementation of a first naive behavior

The first point above will be done in #17 , the second has already a skeleton in quick_start_tutorial.ipynb. Two things have to be done:

- Move the notebook controller description in a dedicated notebook. Improve it to explain:
    - How to access and modify entity attributes
    - How to make a step, a run and a stop
    - Maybe other things 
    - Remove the part on behavior as functions, this will be in session 2
- Make a new notebook with the third point above (at the start of the PR description), called session 1
- Make a new notebook called session 2, inspired from session 2 of pyvrep epuck (reuse text from there and adapt)

### Steps to Reproduce
[//]: # (List the steps to reproduce the issue.)

### Environment (Optional)
- OS: 
- Browser: 
- Python Version:
- Package Version: 

### Screenshots (Optional)
[//]: # (If applicable, add screenshots to help explain the issue.)

**Comment by corentinlger** [comment]
Done in dev branch.
