### ISSUE TITLE
Decide what name the general case of behaviors or routines should have

### ISSUE THREAD

**Issue by Marsolo1** [clement-moulin-frier/vivarium#44]
### Description
As of now, the behaviors defined in the `Agent` class of notebook_controller.py are a specific case of the `routine` methods defined in the base class `Entity`. We should decide whether the behaviors should be recoded as such (for now they are a modified copy-paste of the routines), and what name to give the general case (routine or behavior)

**Comment by corentinlger** [comment]
We kept behaviors and routines names for the notebook controller.
