### ISSUE TITLE
Intregrate text from the project Clément is currently writing

### ISSUE THREAD

**Issue by clement-moulin-frier** [clement-moulin-frier/vivarium#56]
### Description
I currently writing a document explaining the main ideas behind the vivarium. Once I will have finished it (by the end of this week) we should integrate part of this text and figures in the README.

### Steps to Reproduce
[//]: # (List the steps to reproduce the issue.)

### Environment (Optional)
- OS: 
- Browser: 
- Python Version:
- Package Version: 

### Screenshots (Optional)
[//]: # (If applicable, add screenshots to help explain the issue.)

**Comment by corentinlger** [comment]
Updated readme in dev branch.
