### ISSUE TITLE
Improve PR 57

### ISSUE THREAD

**Issue by corentinlger** [clement-moulin-frier/vivarium#71]
### Description
[//]: # (Provide a clear and concise description of the issue.)

To improve  PR #57  : 

- rename n_agents max_agents etc ... in the whole pipeline 
- rename nve_state entities_state
- add either list of values or value options to init functions 
- fix PRNG keys mechanism

**Comment by Marsolo1** [comment]
To add to this I think it is possible to create the default yaml config file automatically using the init functions or the state classes
