### ISSUE TITLE
Rename remaining NVE-based variable

### ISSUE THREAD

**Issue by clement-moulin-frier** [clement-moulin-frier/vivarium#77]
### Description
While working on #76 I noticed that we still use "nve" in a few variable names. This includes:

- `AgentState.nve_idx`. However, renaming it as `AgentState.entity_idx`is not ideal, since we already have `EntitiesState.entity_idx`. @corentinlger Do you have an idea about how we could name it? (idem for `ObjectState`)
- Also the `StateChange`message in simulator.proto has a field `nve_idx``

I also recommend to stick to singular instead of plural as a convention, i.e. renaming:
- `EntitiesState` -> `EntityState`
- Idem for `State.entities_state``
- Check if there are others

**Comment by corentinlger** [comment]
To make it clearer, we could rename ```AgentState.nve_idx``` ```AgentState.entity_state_idx``` ? (idem for  ```ObjectState.nve_idx```)

If it's ok I'll also rename entities* to entity*.

**Comment by clement-moulin-frier** [comment]
Thanks for the proposition. It makes sense, although distinguishing between `EntityState.entity_idx` and `AgentState.entity_state_idx` might not be super intuitive for external users. 

Let's use this thread to discuss this a bit more, trying to find a naming that makes the most sense on the long term.

Here is another proposition:

```python
@dataclass
class ParticleState(simulate.NVEState):
    """
    Global attributes of all particles, independently of their entity type
    """
    entity_type: util.Array
    entity_idx: util.Array  # idx in an EntityState (e.g. AgentState)
    diameter: util.Array
    friction: util.Array
    exists: util.Array

    @property
    def velocity(self) -> util.Array:
        return self.momentum / self.mass

@dataclass
class EntityState:
    """
    Attributes of a specific entity type. Subclasses inheriting from it can specify attributes that concern only a specific entity type
    """
    particle_idx: util.Array  # idx in ParticleState

@dataclass
class AgentState(EntityState):
    prox: util.Array
    motor: util.Array
    behavior: util.Array
    wheel_diameter: util.Array
    speed_mul: util.Array
    max_speed: util.Array
    theta_mul: util.Array
    proxs_dist_max: util.Array
    proxs_cos_min: util.Array
    color: util.Array


@dataclass
class ObjectState(EntityState):
    color: util.Array
```

I think this is the good structure, although I'm not fully sure about the naming convention. The main drawback is that it introduces another term, Particle, which at the end is quite synonym of Entity. The distinction here is that `ParticleState` defines attributes that are common to all entities, whatever their type ; while subclasses of `EntityState` define attributes that are specific to a single entity type.

Let me know what you think or we can discuss it in the meeting tomorrow.
